environment         = "dev"
aws_region          = "us-east-1"
vpc_cidr            = "10.0.0.0/16"
availability_zones  = ["us-east-1a", "us-east-1b"]
db_name             = "metrichive"
db_username         = "metrichive_admin"
db_password         = "MetricHiveDevSecret2026!"
rds_instance_class  = "db.t4g.micro"
rds_multi_az        = false
ecr_repository_name = "metrichive"
