# application.yml (base configuration) add something in here if you want to apply it to every profile
spring:
  profiles:
    active: dev  # Default to dev
  application:
    name: metrichive
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

metrichive:
  rate-limits:
    plans:
      free:
        capacity: 20
        refill-tokens: 20
        refill-duration: 1m
      basic:
        capacity: 100
        refill-tokens: 100
        refill-duration: 1m
      pro:
        capacity: 1000
        refill-tokens: 1000
        refill-duration: 1m

---
# application-dev.yml
spring:

  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/metrichive_dev
    username: metrichive
    password: metrichive123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: MetricHivePool
  jpa:
    hibernate:
      ddl-auto: update  # OK for dev only
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  cache:
    type: redis
    redis:
      time-to-live: 300000

---
# application-prod.yml
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/metrichive_prod
    username: ${DB_USERNAME:metrichive} # ❌ fallback exposed in source code, this is wrong. CHANGE IT
    #WHY? BECAUSE IF db_username is wrong then it silently uses the other password. in production
    #you shouldnt silently fail. fail loudly.
    #password: ${DB_PASSWORD}  # ✅ throws error if not set — which is what you want
    password: ${DB_PASSWORD:metrichive123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: MetricHivePool
  jpa:
    hibernate:
      ddl-auto: none  # IMPORTANT: No schema changes in production
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
  flyway:
    enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 300000



---
# application-test.yml
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false