apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrichive
  labels:
    app: metrichive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrichive
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: metrichive
    spec:
      containers:
        - name: metrichive
          image: metrichive:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/metrichive_dev"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: metrichive-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metrichive-secret
                  key: DB_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
