apiVersion: v1
kind: Secret
metadata:
  name: metrichive-secret
  labels:
    app: metrichive
type: Opaque
stringData:
  DB_USERNAME: metrichive
  DB_PASSWORD: metrichive123
  POSTGRES_DB: metrichive_dev
